### ISSUE TITLE
use disgord.Snowflake not snowflake.Snowflake

### ISSUE THREAD

**Issue by andersfylling** [pazuzu156/persephone#1]
Hey, awesome to see you're using disgord!

Just wanted to let you know that using disgord.Snowflake instead of snowflake.Snowflake/ID will make your project safe whenever disgord upgrades the snowflake dependency.

disgord should upgrade to snowflake v4 soon, and as an example this would break your current codebase. I'm sorry about not haven written docs about this, so figured I'd jump in and let you know :)

**Comment by pazuzu156** [comment]
Thanks for the heads up. Been working with Go for a little over a month, so this has been a good project to work with. Disgord has also been the most complete discord api library for such a project, with the aurora command router.

With disgord.Snowflake, is that in the current version release (which is what I'm currently using) or is it part of the master branch?

**Comment by pazuzu156** [comment]
\>.< please ignore that question, probably would have helped to look at the source code first. Lol
